import React, { useState } from 'react';
import { Project, Language, ProjectFile } from '../types';
import { Globe, Sparkles, Check, Copy, Code, FileText, X, Rocket } from 'lucide-react';

interface SEOHelperModalProps {
  project: Project;
  language: Language;
  isOpen: boolean;
  onClose: () => void;
  onInjectSEOFiles: (newFiles: ProjectFile[]) => void;
}

export const SEOHelperModal: React.FC<SEOHelperModalProps> = ({
  project,
  language,
  isOpen,
  onClose,
  onInjectSEOFiles,
}) => {
  if (!isOpen) return null;

  const isAr = language === 'ar';

  const [title, setTitle] = useState(project.name || 'My Application');
  const [description, setDescription] = useState(
    project.description || 'High-performance web app powered by CodeVortex Cloud.'
  );
  const [keywords, setKeywords] = useState('cloud, react, web app, codevortex, fast, saas');
  const [canonicalUrl, setCanonicalUrl] = useState(`https://${project.id}.codevortex.app`);
  const [copied, setCopied] = useState(false);
  const [injectedSuccess, setInjectedSuccess] = useState(false);

  const generatedSitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${canonicalUrl}</loc>
    <lastmod>${new Date().toISOString().split('T')[0]}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
</urlset>`;

  const generatedRobots = `User-agent: *
Allow: /
Sitemap: ${canonicalUrl}/sitemap.xml`;

  const generatedMetaHtml = `<!-- SEO Meta Tags Generated by CodeVortex Engine -->
<title>${title}</title>
<meta name="description" content="${description}" />
<meta name="keywords" content="${keywords}" />
<link rel="canonical" href="${canonicalUrl}" />

<!-- Open Graph / Facebook / WhatsApp -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${canonicalUrl}" />
<meta property="og:title" content="${title}" />
<meta property="og:description" content="${description}" />
<meta property="og:image" content="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80" />

<!-- Twitter Cards -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content="${canonicalUrl}" />
<meta name="twitter:title" content="${title}" />
<meta name="twitter:description" content="${description}" />`;

  const handleInjectFiles = () => {
    const sitemapFile: ProjectFile = { path: 'sitemap.xml', content: generatedSitemap };
    const robotsFile: ProjectFile = { path: 'robots.txt', content: generatedRobots };

    // Update index.html if exists
    let updatedFiles: ProjectFile[] = [sitemapFile, robotsFile];

    const indexFile = project.files.find((f) => f.path === 'index.html');
    if (indexFile) {
      let updatedHtml = indexFile.content;
      if (updatedHtml.includes('<head>')) {
        updatedHtml = updatedHtml.replace('<head>', `<head>\n  ${generatedMetaHtml}`);
      } else {
        updatedHtml = `${generatedMetaHtml}\n${updatedHtml}`;
      }
      updatedFiles.push({ path: 'index.html', content: updatedHtml });
    }

    onInjectSEOFiles(updatedFiles);
    setInjectedSuccess(true);
    setTimeout(() => {
      setInjectedSuccess(false);
      onClose();
    }, 1500);
  };

  const handleCopyMeta = () => {
    navigator.clipboard.writeText(generatedMetaHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-xl font-sans animate-in fade-in">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-cyan-500/30 rounded-3xl p-6 sm:p-8 shadow-2xl overflow-hidden text-slate-100 space-y-6 max-h-[90vh] flex flex-col">
        {/* Glow Header Background */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-24 bg-gradient-to-r from-emerald-500/20 via-cyan-500/20 to-blue-500/20 blur-2xl rounded-full pointer-events-none" />

        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 rtl:left-5 rtl:right-auto p-2 rounded-xl bg-slate-800/80 hover:bg-slate-700 text-slate-400 hover:text-white transition-all"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="text-center space-y-2 relative shrink-0">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-emerald-400 to-cyan-500 flex items-center justify-center mx-auto text-slate-950 font-black shadow-lg shadow-emerald-500/20">
            <Globe className="w-6 h-6 stroke-[2.5]" />
          </div>

          <h2 className="text-xl sm:text-2xl font-black text-white">
            {isAr ? 'أداة تحسين SEO والظهور في محركات البحث' : 'SEO & Indexing Optimizer Helper'}
          </h2>

          <p className="text-xs text-slate-400 max-w-md mx-auto">
            {isAr
              ? 'توليد ملفات sitemap.xml و robots.txt وسوم OpenGraph تلقائياً لضمان تصدر تطبيقك في Google.'
              : 'Auto-generate sitemap.xml, robots.txt, and Open Graph Meta tags for top search ranking.'}
          </p>
        </div>

        {/* Form Inputs */}
        <div className="flex-1 overflow-y-auto space-y-4 text-xs pr-1">
          <div className="space-y-1">
            <label className="font-bold text-slate-300">{isAr ? 'عنوان الموقع (Meta Title):' : 'Site Title (Meta Title):'}</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-slate-100 focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div className="space-y-1">
            <label className="font-bold text-slate-300">{isAr ? 'الوصف التوضيحي (Meta Description):' : 'Meta Description:'}</label>
            <textarea
              rows={2}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-slate-100 focus:outline-none focus:border-cyan-500"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="font-bold text-slate-300">{isAr ? 'الكلمات المفتاحية (Keywords):' : 'Keywords:'}</label>
              <input
                type="text"
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-slate-100 focus:outline-none focus:border-cyan-500"
              />
            </div>

            <div className="space-y-1">
              <label className="font-bold text-slate-300">{isAr ? 'الرابط الأساسي (Canonical URL):' : 'Canonical Domain:'}</label>
              <input
                type="text"
                value={canonicalUrl}
                onChange={(e) => setCanonicalUrl(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-slate-100 focus:outline-none focus:border-cyan-500"
              />
            </div>
          </div>

          {/* Generated Snippet Preview */}
          <div className="space-y-2 pt-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-300 flex items-center gap-1.5">
                <FileText className="w-4 h-4 text-emerald-400" />
                <span>Generated HTML Meta Tags:</span>
              </span>
              <button
                type="button"
                onClick={handleCopyMeta}
                className="flex items-center gap-1 text-slate-400 hover:text-cyan-400 font-bold"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? (isAr ? 'تم النسخ' : 'Copied') : (isAr ? 'نسخ' : 'Copy Code')}</span>
              </button>
            </div>

            <pre className="p-3 bg-slate-950 rounded-2xl border border-slate-800 font-mono text-[11px] text-cyan-300/90 overflow-x-auto max-h-36">
              {generatedMetaHtml}
            </pre>
          </div>
        </div>

        {/* Modal Action Footer */}
        <div className="pt-3 border-t border-slate-800 flex items-center justify-end gap-3 shrink-0 text-xs">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 font-bold text-slate-300"
          >
            {isAr ? 'إلغاء' : 'Cancel'}
          </button>

          <button
            type="button"
            onClick={handleInjectFiles}
            disabled={injectedSuccess}
            className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-emerald-400 to-cyan-500 text-slate-950 font-black flex items-center gap-2 shadow-lg shadow-emerald-500/20 hover:scale-[1.02] transition-all"
          >
            {injectedSuccess ? (
              <>
                <Check className="w-4 h-4 text-slate-950 stroke-[3]" />
                <span>{isAr ? 'تم دمج ملفات SEO بنجاح!' : 'SEO Files Injected!'}</span>
              </>
            ) : (
              <>
                <Rocket className="w-4 h-4 fill-current text-slate-950" />
                <span>{isAr ? 'حقن ملفات SEO إلى مشروعك' : 'Inject SEO Files to Project'}</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
