import { json, jsonError, uid, isArText } from '@/lib/api';

/**
 * CloudForge — AI Project Generator
 * ------------------------------------------------------------------
 * Tries real AI providers (OpenAI → Anthropic → Gemini) when an API key
 * is configured server-side. Without any key the endpoint still returns
 * a deterministic, keyword-aware starter project — so "Generate App"
 * NEVER fails or hangs on Vercel.
 */

type ProjectFiles = { path: string; content: string }[];

function starterFiles(kind: string, rtl: boolean, prompt: string): ProjectFiles {
  const lang = rtl ? 'ar' : 'en';
  const dir = rtl ? 'rtl' : 'ltr';
  const title = prompt.slice(0, 40) || (rtl ? 'تطبيقي السحابي' : 'My Cloud App');
  const hero = rtl ? 'ابنِ تطبيقك القادم' : 'Build your next app';
  const desc = rtl
    ? 'تطبيق تم توليده بواسطة محرك CloudForge العصبي — جاهز للمعاينة والنشر.'
    : 'Generated by the CloudForge neural engine — ready to preview and deploy.';

  const sections =
    kind === 'ecommerce'
      ? `<section id="products" class="grid"></section>`
      : kind === 'dashboard'
        ? `<section id="stats" class="kpis"></section><table id="tbl"></table>`
        : kind === 'ai'
          ? `<section id="chat" class="chat"><div id="messages"></div></section>`
          : `<section id="features"><h2>Features</h2></section><section id="pricing"><h2>Pricing</h2></section>`;

  return [
    {
      path: 'index.html',
      content: `<!DOCTYPE html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="nav"><strong>CloudForge ⚡</strong></header>
  <main>
    <section class="hero">
      <h1>${hero}</h1>
      <p>${desc}</p>
      <button class="cta">${rtl ? 'ابدأ الآن' : 'Get Started'}</button>
    </section>
    ${sections}
  </main>
  <script src="app.js"></script>
</body>
</html>`,
    },
    {
      path: 'styles.css',
      content: `body { margin: 0; font-family: 'Cairo', system-ui, sans-serif; background: #0B0F19; color: #e2e8f0; }
.nav { display: flex; justify-content: space-between; padding: 1rem 2rem; border-bottom: 1px solid #1e293b; }
.hero { padding: 5rem 2rem; text-align: center; }
.cta { background: linear-gradient(90deg, #00F2FE, #7928CA); border: 0; padding: 0.9rem 1.6rem; border-radius: 12px; font-weight: 700; color: #0B0F19; cursor: pointer; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem; padding: 2rem; }
.card { background: #111827; border: 1px solid #1e293b; border-radius: 14px; padding: 1rem; }
.kpis { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 1rem; padding: 2rem; }
.kpi { background: #111827; border: 1px solid #1e293b; border-radius: 14px; padding: 1rem; }
table { width: calc(100% - 4rem); margin: 0 2rem; border-collapse: collapse; }
td, th { border-bottom: 1px solid #1e293b; padding: 0.7rem; text-align: left; }`,
    },
    {
      path: 'app.js',
      content: `// ${title} — generated by CloudForge AI Engine
console.log('🚀 CloudForge app is running on port 3000');
document.querySelector('.cta')?.addEventListener('click', () => {
  alert(${JSON.stringify(rtl ? 'مرحباً بك في CloudForge! 🚀' : 'Welcome to CloudForge! 🚀')});
});
const grid = document.querySelector('.grid');
if (grid) {
  const items = ['Product A', 'Product B', 'Product C'];
  grid.innerHTML = items.map((n) => \`<div class="card"><h3>\${n}</h3><p>Ready to deploy</p></div>\`).join('');
}`,
    },
  ];
}

function detectKind(prompt: string): 'saas' | 'ecommerce' | 'dashboard' | 'ai' {
  const p = (prompt || '').toLowerCase();
  if (/shop|store|commerce|متجر|تجارة/.test(p)) return 'ecommerce';
  if (/dashboard|admin|analytics|لوحة|تحليلات/.test(p)) return 'dashboard';
  if (/chat|ai|agent|assistant|مساعد|ذكاء/.test(p)) return 'ai';
  return 'saas';
}

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const { prompt, model, language, projectType } = body as {
      prompt?: string;
      model?: string;
      language?: string;
      projectType?: string;
    };

    const rtl = isArText(prompt || '') || language === 'ar';
    const kind = detectKind(prompt || '');
    const fallbackFiles = starterFiles(kind, rtl, prompt || '');

    // ---- Real AI path (server-side only, keys never leave the server) ----
    const openaiKey = process.env.OPENAI_API_KEY;
    const anthropicKey = process.env.ANTHROPIC_API_KEY;
    const geminiKey = process.env.GEMINI_API_KEY;

    if (openaiKey || anthropicKey || geminiKey) {
      const system =
        'You are CloudForge, an expert full-stack architect. Given a user prompt, return STRICT JSON: ' +
        '{"title": string, "description": string, "isRTL": boolean, "files": [{"path": string, "content": string}]}. ' +
        'Generate 3 files (index.html, styles.css, app.js) of production-quality starter code, dark theme, RTL when Arabic.';

      let completion: string | null = null;

      try {
        if (openaiKey) {
          const res = await fetch('https://api.openai.com/v1/chat/completions', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${openaiKey}`,
            },
            body: JSON.stringify({
              model: model === 'gpt-4o' ? 'gpt-4o' : 'gpt-4o-mini',
              response_format: { type: 'json_object' },
              messages: [
                { role: 'system', content: system },
                { role: 'user', content: prompt || 'Build a SaaS landing page' },
              ],
            }),
          });
          const data = await res.json();
          completion = data?.choices?.[0]?.message?.content ?? null;
        }
      } catch {
        completion = null;
      }

      if (!completion && anthropicKey) {
        try {
          const res = await fetch('https://api.anthropic.com/v1/messages', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-api-key': anthropicKey,
              'anthropic-version': '2023-06-01',
            },
            body: JSON.stringify({
              model: 'claude-3-5-haiku-latest',
              max_tokens: 4000,
              messages: [
                { role: 'user', content: `${system}\n\nPrompt: ${prompt || 'Build a SaaS landing page'}` },
              ],
            }),
          });
          const data = await res.json();
          completion = data?.content?.[0]?.text ?? null;
        } catch {
          completion = null;
        }
      }

      if (!completion && geminiKey) {
        try {
          const res = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${geminiKey}`,
            {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                contents: [{ parts: [{ text: `${system}\n\nPrompt: ${prompt || 'Build a SaaS landing page'}` }] }],
              }),
            }
          );
          const data = await res.json();
          completion = data?.candidates?.[0]?.content?.parts?.[0]?.text ?? null;
        } catch {
          completion = null;
        }
      }

      if (completion) {
        const cleaned = completion.replace(/^```json|^```|```$/g, '').trim();
        const parsed = JSON.parse(cleaned);
        if (parsed && Array.isArray(parsed.files) && parsed.files.length > 0) {
          return json({
            title: parsed.title || 'AI Generated Project',
            description: parsed.description || 'Generated by CloudForge AI Engine',
            files: parsed.files,
            isRTL: parsed.isRTL ?? rtl,
            provider: 'ai',
          });
        }
      }
    }

    // ---- Deterministic fallback: never empty, never fails ----
    return json({
      title: (prompt || 'CloudForge Project').slice(0, 60),
      description: 'Generated by the CloudForge neural engine (offline mode) — ready to preview and deploy.',
      files: fallbackFiles,
      isRTL: rtl,
      provider: 'fallback',
    });
  } catch (err) {
    return jsonError('AI generation failed', 500, String(err));
  }
}
